/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cwm_wearablesdk_JniManager */

#ifndef _Included_cwm_wearablesdk_JniManager
#define _Included_cwm_wearablesdk_JniManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getSyncIntelligentCommand
 * Signature: ([ZI[B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getSyncIntelligentCommand
  (JNIEnv *, jobject, jbooleanArray, jint, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getSyncBodyCommandCommand
 * Signature: ([I[B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getSyncBodyCommandCommand
  (JNIEnv *, jobject, jintArray, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getSyncCurrentCommand
 * Signature: ([I[B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getSyncCurrentCommand
  (JNIEnv *, jobject, jintArray, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getRequestBatteryCommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getRequestBatteryCommand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getTabataCommand
 * Signature: (IIII[B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getTabataCommand
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getCwmInformation
 * Signature: (I[B[I)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getCwmInformation
  (JNIEnv *, jobject, jint, jbyteArray, jintArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getType
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_cwm_wearablesdk_JniManager_getType
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getSleepLogCommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getSleepLogCommand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getRequestSwVersionCommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getRequestSwVersionCommand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getSwitchOTACommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getSwitchOTACommand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getCwmSleepInfomation
 * Signature: (I[B[F)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getCwmSleepInfomation
  (JNIEnv *, jobject, jint, jbyteArray, jfloatArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getSedentaryRemindTimeCommand
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getSedentaryRemindTimeCommand
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getReadFlashCommand
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getReadFlashCommand
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getRequestMaxLogPacketsCommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getRequestMaxLogPacketsCommand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getGestureListCommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getGestureListCommand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getGestureListInfomation
 * Signature: (I[B[I)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getGestureListInfomation
  (JNIEnv *, jobject, jint, jbyteArray, jintArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getRecordSensorToFlashCommand
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getRecordSensorToFlashCommand
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     cwm_wearablesdk_JniManager
 * Method:    getRequestEraseProgressCommand
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cwm_wearablesdk_JniManager_getRequestEraseProgressCommand
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
